name: Node CI

on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone my repo
        uses: actions/checkout@v1

      - name: install
        run: make install

      - name: lint
        run: make lint
